/**
 * Deterministic Korean menu translation.
 *
 * Exact dish names take priority. Remaining Korean is scanned left-to-right with
 * the longest available culinary term. Unmatched text is romanized only after
 * every known food term has been translated, so a house or brand name can stay
 * identifiable without presenting romanization as a semantic translation.
 */

const INITIAL = [
  "g", "kk", "n", "d", "tt", "r", "m", "b", "pp", "s", "ss", "", "j", "jj", "ch", "k", "t", "p", "h",
] as const;
const VOWEL = [
  "a", "ae", "ya", "yae", "eo", "e", "yeo", "ye", "o", "wa", "wae", "oe", "yo", "u", "wo", "we", "wi", "yu", "eu", "ui", "i",
] as const;
const FINAL = [
  "", "k", "k", "ks", "n", "nj", "nh", "t", "l", "lk", "lm", "lb", "ls", "lt", "lp", "lh", "m", "p", "ps", "t", "t", "ng", "t", "t", "k", "t", "p", "h",
] as const;

/** High-frequency complete dishes and conventional English menu names. */
export const EXACT_MENU_TRANSLATIONS: Readonly<Record<string, string>> = {
  "된장찌개": "soybean paste stew",
  "김치찌개": "kimchi stew",
  "볶음밥": "fried rice",
  "짬뽕": "spicy seafood noodle soup",
  "비빔냉면": "spicy mixed cold noodles",
  "아메리카노": "Americano",
  "짜장면": "black bean noodles",
  "자장면": "black bean noodles",
  "물냉면": "cold noodles in broth",
  "우동": "udon",
  "공기밥": "bowl of rice",
  "라면": "ramyeon",
  "짬뽕밥": "spicy seafood soup with rice",
  "수육": "boiled meat slices",
  "순대국밥": "blood sausage soup with rice",
  "순대국": "blood sausage soup",
  "잡채밥": "stir-fried glass noodles with rice",
  "카페라떼": "cafe latte",
  "비빔국수": "spicy mixed noodles",
  "군만두": "fried dumplings",
  "콩국수": "noodles in cold soy milk",
  "만두국": "dumpling soup",
  "만둣국": "dumpling soup",
  "칼국수": "knife-cut noodle soup",
  "육개장": "spicy beef soup",
  "제육볶음": "spicy stir-fried pork",
  "냉면": "cold noodles",
  "청국장": "fermented soybean stew",
  "간짜장": "dry-style black bean noodles",
  "떡볶이": "tteokbokki",
  "순대": "Korean blood sausage",
  "회덮밥": "sashimi rice bowl",
  "갈비탕": "beef short rib soup",
  "감자전": "potato pancake",
  "해물파전": "seafood and green onion pancake",
  "잔치국수": "banquet noodle soup",
  "고등어구이": "grilled mackerel",
  "계란말이": "rolled omelet",
  "두부김치": "tofu with stir-fried kimchi",
  "새우볶음밥": "shrimp fried rice",
  "오징어볶음": "spicy stir-fried squid",
  "비빔밥": "bibimbap",
  "설렁탕": "ox bone soup",
  "양장피": "seafood and vegetables with mustard sauce",
  "잡탕밥": "rice with assorted seafood and vegetables",
  "계란찜": "steamed eggs",
  "삼선짬뽕": "premium seafood noodle soup",
  "에스프레소": "espresso",
  "전복죽": "abalone porridge",
  "쫄면": "spicy chewy noodles",
  "낙지볶음": "spicy stir-fried octopus",
  "돼지국밥": "pork soup with rice",
  "육회": "Korean-style beef tartare",
  "육회비빔밥": "beef tartare bibimbap",
  "삼겹살": "pork belly",
  "술국": "hearty blood sausage soup",
  "소주": "soju",
  "곰탕": "beef bone soup",
  "내장국밥": "offal soup with rice",
  "닭도리탕": "spicy braised chicken",
  "닭볶음탕": "spicy braised chicken",
  "바닐라라떼": "vanilla latte",
  "팔보채": "stir-fried mixed seafood and vegetables",
  "새우튀김": "shrimp tempura",
  "해장국": "hangover soup",
  "도가니탕": "ox knee cartilage soup",
  "떡국": "rice cake soup",
  "맥주": "beer",
  "삼선볶음밥": "premium seafood fried rice",
  "떡만두국": "rice cake and dumpling soup",
  "떡만둣국": "rice cake and dumpling soup",
  "만두": "dumplings",
  "유산슬": "shredded seafood and meat stir-fry",
  "탕수육": "sweet-and-sour pork",
  "파전": "green onion pancake",
  "김밥": "gimbap",
  "순두부찌개": "soft tofu stew",
  "음료수": "soft drink",
  "짜장밥": "black bean sauce with rice",
  "도토리묵": "acorn jelly",
  "삼선우동": "premium seafood udon",
  "카푸치노": "cappuccino",
  "갈치조림": "braised hairtail",
  "깐풍기": "spicy garlic fried chicken",
  "마파두부밥": "mapo tofu with rice",
  "매운탕": "spicy fish stew",
  "온면": "warm noodle soup",
  "울면": "thick seafood noodle soup",
  "짜장": "black bean noodles",
  "물회": "spicy raw seafood soup",
  "돌솥비빔밥": "hot stone pot bibimbap",
  "접시만두": "platter of dumplings",
  "고기국수": "meat noodle soup",
  "김치전": "kimchi pancake",
  "따로국밥": "soup with rice served separately",
  "물만두": "boiled dumplings",
  "육전": "pan-fried battered beef slices",
  "편육": "sliced pressed meat",
  "해삼": "sea cucumber",
  "메밀전병": "buckwheat rolls",
  "내장탕": "offal soup",
  "생선구이": "grilled fish",
  "순두부": "soft tofu",
  "굴전": "oyster pancake",
  "누룽지": "scorched rice",
  "대구탕": "cod soup",
  "돈가스": "pork cutlet",
  "돈까스": "pork cutlet",
  "백반": "Korean set meal",
  "비빔막국수": "spicy mixed buckwheat noodles",
  "산낙지": "live octopus",
  "수제비": "hand-torn noodle soup",
  "열무국수": "young-radish kimchi noodles",
  "오뎅탕": "fish cake soup",
  "어묵탕": "fish cake soup",
  "찐만두": "steamed dumplings",
  "소머리국밥": "ox head soup with rice",
  "수육백반": "boiled meat set meal",
  "전복물회": "spicy raw abalone soup",
  "갈치구이": "grilled hairtail",
  "녹두빈대떡": "mung bean pancake",
  "녹두전": "mung bean pancake",
  "닭똥집": "chicken gizzards",
  "동태찌개": "pollock stew",
  "마파두부": "mapo tofu",
  "부추전": "chive pancake",
  "알탕": "fish roe stew",
  "평양냉면": "Pyongyang-style cold noodles",
  "국밥": "soup with rice",
  "꼬리곰탕": "oxtail soup",
  "막국수": "buckwheat noodles",
  "바지락칼국수": "clam knife-cut noodle soup",
  "삼계탕": "ginseng chicken soup",
  "섞어국밥": "mixed-meat soup with rice",
  "왕만두": "large dumplings",
  "해물라면": "seafood ramyeon",
  "고추잡채": "stir-fried peppers and meat",
  "골뱅이무침": "spicy sea-snail salad",
  "깐풍새우": "spicy garlic shrimp",
  "돼지갈비": "pork ribs",
  "모듬전": "assorted savory pancakes",
  "모둠전": "assorted savory pancakes",
  "보리밥": "barley rice",
  "양념치킨": "seasoned fried chicken",
  "옥돔구이": "grilled tilefish",
  "고추짬뽕": "spicy chili seafood noodle soup",
  "닭발": "chicken feet",
  "라조기": "chicken in chili sauce",
  "머리고기": "boiled head-meat slices",
  "삼선짜장": "premium seafood black bean noodles",
  "생삼겹살": "fresh pork belly",
  "생선까스": "fish cutlet",
  "생선가스": "fish cutlet",
  "오뎅": "fish cake",
  "어묵": "fish cake",
  "유산슬밥": "shredded seafood and meat stir-fry with rice",
  "장어탕": "eel soup",
  "회냉면": "cold noodles with raw fish",
  "난자완스": "braised meatballs",
  "도가니수육": "boiled ox knee cartilage slices",
  "라면사리": "extra ramyeon noodles",
  "목살": "pork neck",
  "물막국수": "buckwheat noodles in cold broth",
  "불고기": "bulgogi",
  "빈대떡": "mung bean pancake",
  "얼그레이": "Earl Grey tea",
  "차돌박이": "beef brisket",
  "참치김밥": "tuna gimbap",
  "초코라떼": "chocolate latte",
  "카페모카": "cafe mocha",
  "한우육회": "Korean beef tartare",
  "후라이드치킨": "fried chicken",
  "프라이드치킨": "fried chicken",
  "감자튀김": "french fries",
  "김치볶음밥": "kimchi fried rice",
  "떡라면": "rice cake ramyeon",
  "성게미역국": "sea urchin seaweed soup",
  "유니짜장": "minced-meat black bean noodles",
  "전복뚝배기": "abalone hot-pot stew",
  "추어탕": "loach soup",
  "기스면": "shredded chicken noodle soup",
  "닭백숙": "whole chicken soup",
  "더덕구이": "grilled deodeok root",
  "동파육": "Dongpo-style braised pork belly",
  "레몬에이드": "lemonade",
  "멸치국수": "anchovy noodle soup",
  "문어숙회": "blanched octopus",
  "부대찌개": "army-base stew",
  "전복회": "raw abalone",
  "치즈라면": "cheese ramyeon",
  "항정살": "pork jowl",
  "계란탕": "egg soup",
  "광어": "olive flounder sashimi",
  "국수": "noodles",
  "깐쇼새우": "sweet and spicy crispy shrimp",
  "깐풍육": "spicy garlic pork",
  "아구찜": "spicy braised monkfish",
  "아귀찜": "spicy braised monkfish",
  "족발": "braised pork trotters",
  "보쌈": "boiled pork wraps",
  "닭갈비": "spicy stir-fried chicken",
  "감자탕": "pork back-bone stew",
  "떡갈비": "grilled short-rib patties",
  "쌀국수": "rice noodle soup",
  "밀면": "wheat noodles",
  "초밥": "sushi",
  "사시미": "sashimi",
  "연어초밥": "salmon sushi",
  "장어덮밥": "grilled eel rice bowl",
  "규동": "beef rice bowl",
  "가츠동": "pork cutlet rice bowl",
  "텐동": "tempura rice bowl",
  "오므라이스": "omelet rice",
  "김치찜": "braised kimchi",
  "갈비찜": "braised short ribs",
  "해물찜": "spicy braised seafood",
  "꽃게탕": "blue crab stew",
  "꽃게찜": "steamed blue crab",
  "간장게장": "soy-marinated raw crab",
  "양념게장": "spicy marinated raw crab",
  "닭한마리": "whole chicken hot pot",
  "샤브샤브": "shabu-shabu",
  "두루치기": "spicy stir-fried meat",
  "주꾸미볶음": "spicy stir-fried webfoot octopus",
  "쭈꾸미볶음": "spicy stir-fried webfoot octopus",
  "오징어순대": "stuffed squid",
  "홍어삼합": "fermented skate with pork and kimchi",
  "미역국": "seaweed soup",
  "북엇국": "dried pollock soup",
  "황태국": "dried pollock soup",
  "콩나물국": "soybean sprout soup",
  "계란볶음밥": "egg fried rice",
  "새우만두": "shrimp dumplings",
  "김치만두": "kimchi dumplings",
  "고기만두": "meat dumplings",
  "회국수": "raw fish noodles",
  "메밀소바": "buckwheat soba",
  "판모밀": "chilled buckwheat noodles",
  "토마토파스타": "tomato pasta",
  "크림파스타": "cream pasta",
  "봉골레파스타": "clam pasta",
  "알리오올리오": "aglio e olio",
  "마르게리타": "Margherita pizza",
  "치즈피자": "cheese pizza",
  "고르곤졸라피자": "Gorgonzola pizza",
  "함박스테이크": "hamburger steak",
  "등심돈까스": "pork loin cutlet",
  "안심돈까스": "pork tenderloin cutlet",
  "치즈돈까스": "cheese pork cutlet",
  "치킨까스": "chicken cutlet",
  "아이스아메리카노": "iced Americano",
  "아이스티": "iced tea",
  "녹차라떼": "green tea latte",
  "말차라떼": "matcha latte",
  "고구마라떼": "sweet potato latte",
  "딸기라떼": "strawberry latte",
  "밀크티": "milk tea",
  "레몬차": "lemon tea",
  "유자차": "citron tea",
  "자몽에이드": "grapefruit ade",
  "청포도에이드": "green grape ade",
  "콜라": "cola",
  "사이다": "lemon-lime soda",
  "막걸리": "makgeolli rice wine",
  "동동주": "dongdongju rice wine",
  "유린기": "fried chicken with scallion soy sauce",
  "사리": "extra noodles",
  "주먹밥": "rice balls",
  "라조육": "meat in chili sauce",
  "삼치구이": "grilled Spanish mackerel",
  "쟁반짜장": "platter of black bean noodles",
  "플랫화이트": "flat white",
  "바닐라빈라떼": "vanilla bean latte",
  "제육": "spicy pork",
  "황도": "canned peaches",
  "닭곰탕": "chicken soup",
  "모두부": "whole block of tofu",
  "아포가토": "affogato",
  "오향장육": "five-spice sliced pork",
  "페퍼민트": "peppermint tea",
  "후라이드": "fried chicken",
  "돼지껍데기": "pork skin",
  "껍데기": "pork skin",
  "라볶이": "ramyeon tteokbokki",
  "오리주물럭": "spicy marinated duck stir-fry",
  "메로구이": "grilled Patagonian toothfish",
  "연포탕": "clear octopus soup",
  "칠리새우": "shrimp in chili sauce",
  "무뼈닭발": "boneless chicken feet",
  "차돌된장찌개": "beef brisket soybean paste stew",
  "동그랑땡": "pan-fried meat patties",
  "어향육슬": "Sichuan shredded pork",
  "캐모마일": "chamomile tea",
  "냉모밀": "chilled buckwheat noodles",
  "맛보기수육": "tasting portion of boiled meat slices",
  "양꼬치": "lamb skewers",
  "오돌뼈": "spicy stir-fried pork cartilage",
  "김치말이국수": "cold kimchi noodle soup",
  "우족탕": "ox foot soup",
  "치즈떡볶이": "cheese tteokbokki",
  "낙지탕탕이": "chopped raw octopus",
  "돌멍게": "sea squirt",
  "손칼국수": "handmade knife-cut noodle soup",
  "장칼국수": "spicy soybean paste knife-cut noodle soup",
  "치즈김밥": "cheese gimbap",
  "치킨가라아게": "chicken karaage",
  "어향가지": "Sichuan eggplant",
  "콜드브루": "cold brew",
  "물메기탕": "sea raven soup",
  "복분자": "black raspberry wine",
  "복숭아아이스티": "peach iced tea",
  "지삼선": "stir-fried potato, eggplant, and pepper",
  "팥빙수": "red bean shaved ice",
  "가지튀김": "fried eggplant",
  "마늘통닭": "garlic whole fried chicken",
  "먹태": "dried pollock",
  "선지국밥": "ox-blood soup with rice",
  "염통": "heart skewers",
  "옻닭": "lacquer-tree chicken soup",
  "쟁반막국수": "platter of spicy mixed buckwheat noodles",
  "전가복": "braised mixed seafood",
  "쥐포": "dried filefish",
  "충무김밥": "Chungmu-style gimbap",
  "폐업": "closed",
  "냉콩국수": "cold soy milk noodles",
  "뼈해장국": "pork bone hangover soup",
  "소갈비살": "beef rib meat",
  "짬뽕국물": "spicy seafood broth",
  "경장육슬": "shredded pork with sweet bean sauce",
  "꿔바로우": "crispy sweet-and-sour pork",
  "녹두지짐": "mung bean pancake",
  "돼지두루치기": "spicy stir-fried pork",
  "오무라이스": "omelet rice",
  "해파리냉채": "chilled jellyfish salad",
  "과메기": "half-dried saury",
  "노가리": "dried young pollock",
  "동치미국수": "radish-water-kimchi noodles",
  "똠얌꿍": "tom yum goong",
  "바닐라 라떼": "vanilla latte",
  "꼬막": "cockles",
  "냄비우동": "pot udon",
  "머릿고기": "boiled head-meat slices",
  "비빔만두": "dumplings with spicy mixed vegetables",
  "오삼불고기": "spicy squid and pork bulgogi",
  "우동사리": "extra udon noodles",
  "중화비빔밥": "Chinese-style spicy seafood rice bowl",
  "콩비지": "ground soybean stew",
  "가오리찜": "steamed skate",
  "소금빵": "salt bread",
  "육사시미": "beef sashimi",
  "팥칼국수": "red bean knife-cut noodles",
  "까르보나라": "carbonara",
  "아인슈페너": "Einspanner coffee",
  "오소리감투": "boiled pork stomach",
  "나시고랭": "nasi goreng",
  "차": "tea",
  "굴": "oyster",
  "콩": "soybean",
  "쌀": "rice",
  "삼선간짜장": "premium seafood dry-style black bean noodles",
  "사천짜장": "Sichuan-style black bean noodles",
  "삼선울면": "premium seafood thick noodle soup",
  "굴짬뽕": "oyster spicy seafood noodle soup",
  "알밥": "fish roe rice bowl",
  "생굴": "fresh oysters",
  "생두부": "fresh tofu",
  "순대만국밥": "blood sausage-only soup with rice",
  "굴떡국": "oyster rice cake soup",
  "생대구탕": "fresh cod soup",
  "회비빔밥": "sashimi bibimbap",
  "핸드드립": "pour-over coffee",
  "도루묵찌개": "sandfish stew",
  "매생이탕": "seaweed soup",
  "번데기탕": "silkworm pupa soup",
  "자몽차": "grapefruit tea",
  "개불": "spoon worm",
  "꼬막비빔밥": "cockle bibimbap",
  "돔베고기": "Jeju-style boiled pork slices",
  "돼지불백": "pork bulgogi set meal",
  "똥집": "chicken gizzards",
  "머리국밥": "head-meat soup with rice",
  "분짜": "bun cha",
  "야끼우동": "stir-fried udon",
  "건두부볶음": "stir-fried tofu skin",
  "고등어봉초밥": "pressed mackerel sushi",
  "냉국수": "chilled noodles",
  "떡사리": "extra rice cakes",
  "복국": "pufferfish soup",
  "왕새우튀김": "fried jumbo shrimp",
  "잡탕": "assorted soup",
  "시메사바": "vinegar-cured mackerel",
  "카모마일": "chamomile tea",
  "향라육슬": "spicy aromatic shredded pork",
  "후토마끼": "futomaki",
  "도토리전": "acorn jelly pancake",
  "롱블랙": "long black coffee",
  "묵사발": "acorn jelly in cold broth",
  "번데기": "silkworm pupae",
  "쫄볶이": "chewy noodles with tteokbokki",
  "칼제비": "knife-cut and hand-torn noodle soup",
  "팟타이": "pad Thai",
  "한라봉에이드": "Hallabong citrus ade",
  "단팥죽": "sweet red bean porridge",
  "돼지머리국밥": "pork head-meat soup with rice",
  "마라룽샤": "mala crayfish",
  "물밀면": "wheat noodles in cold broth",
  "보말죽": "top-shell porridge",
  "뼈없는닭발": "boneless chicken feet",
  "시저샐러드": "Caesar salad",
  "시저 샐러드": "Caesar salad",
  "암뽕": "boiled pork uterus",
  "어복쟁반": "beef and vegetable hot pot",
  "오리로스": "grilled sliced duck",
  "오이무침": "seasoned cucumber salad",
  "오징어데침": "blanched squid",
  "우니": "sea urchin",
  "자리물회": "spicy raw damselfish soup",
  "즉석떡볶이": "table-cooked tteokbokki",
  "청귤에이드": "green tangerine ade",
  "함흥냉면": "Hamheung-style cold noodles",
  "호박전": "squash pancake",
  "갑오징어": "cuttlefish",
  "고갈비": "grilled seasoned mackerel",
  "냉우동": "chilled udon",
  "도다리쑥국": "flounder and mugwort soup",
  "떡만두": "rice cake and dumplings",
  "물국수": "noodles in broth",
  "물짜장": "soupy black bean noodles",
  "백짬뽕": "mild white seafood noodle soup",
  "비빔밀면": "spicy mixed wheat noodles",
  "소막창": "beef abomasum",
  "순대만": "blood sausage only",
  "얼큰수제비": "spicy hand-torn noodle soup",
  "찐빵": "steamed bun",
  "찰순대": "sticky-rice blood sausage",
  "특곰탕": "special beef bone soup",
  "타코와사비": "octopus with wasabi",
  "플랫 화이트": "flat white",
  "모츠나베": "offal hot pot",
  "아포카토": "affogato",
  "어니언링": "onion rings",
  "카이센동": "seafood rice bowl",
  "덴뿌라": "tempura",
  "류산슬": "shredded seafood and meat stir-fry",
  "류산슬밥": "shredded seafood and meat stir-fry with rice",
  "멘보샤": "shrimp toast",
  "사천탕면": "Sichuan spicy noodle soup",
  "사케동": "salmon rice bowl",
  "애호박찌개": "Korean squash stew",
  "우거지해장국": "dried cabbage hangover soup",
  "치마살": "beef flank steak",
  "카라멜라떼": "caramel latte",
  "카레라이스": "curry rice",
  "코다리찜": "braised semi-dried pollock",
  "가지덮밥": "eggplant rice bowl",
  "광동밥": "Cantonese-style rice bowl",
  "깻잎전": "perilla leaf pancake",
  "꼬마김밥": "mini gimbap",
  "녹차": "green tea",
  "닭날개": "chicken wings",
  "도미머리조림": "braised sea bream head",
  "등골": "spinal cord",
  "마라샹궈": "mala xiang guo",
  "병어조림": "braised silver pomfret",
  "병어회": "silver pomfret sashimi",
  "보말칼국수": "top-shell knife-cut noodle soup",
  "북경오리": "Peking duck",
  "사천짬뽕": "Sichuan-style spicy seafood noodle soup",
  "석화": "oysters on the half shell",
  "쏨땀": "som tam",
  "야끼밥": "stir-fried rice",
  "연유라떼": "condensed milk latte",
  "우렁된장찌개": "river-snail soybean paste stew",
  "우육면": "beef noodle soup",
  "원조김밥": "original gimbap",
  "재첩국": "freshwater clam soup",
  "찹쌀순대": "sticky-rice blood sausage",
  "탄탄면": "dan dan noodles",
  "특양구이": "grilled beef tripe",
  "가오리무침": "seasoned skate salad",
  "굴밥": "oyster rice",
  "굴보쌈": "oysters with boiled pork wraps",
  "굴튀김": "fried oysters",
  "낙지초무침": "tangy seasoned octopus salad",
  "냉메밀": "chilled buckwheat noodles",
  "된장술밥": "rice in soybean paste broth",
  "몸국": "Jeju pork and seaweed soup",
  "묵무침": "seasoned acorn jelly salad",
  "묵밥": "acorn jelly with rice",
  "생목살": "fresh pork neck",
  "생삼겹": "fresh pork belly",
  "성게알": "sea urchin roe",
  "쌀떡볶이": "rice-cake tteokbokki",
  "양갈비": "lamb chops",
  "양곰탕": "beef tripe soup",
  "양무침": "seasoned beef tripe salad",
  "왕돈까스": "large pork cutlet",
  "장국밥": "soybean paste soup with rice",
  "찜닭": "soy-braised chicken",
  "칡냉면": "arrowroot cold noodles",
  "초등학생": "elementary school student",
  "미취학아동": "preschool child",
  "성인": "adult",
  "주말 및 공휴일": "weekends and public holidays",
  "5찬과 부추전이 제공됩니다(공기밥미포함)": "includes five side dishes and a chive pancake (rice not included)",
  "사장님이 직접 끓여서 만드는 기가 막힌 모주": "house-made moju simmered by the owner",
  "매일 아침 직접 손질하고 준비합니다.": "prepared fresh every morning",
  "오코노미야끼": "okonomiyaki",
  "팟카파오무쌉": "pad kra pao moo sap",
  "밀크쉐이크": "milkshake",
  "에그타르트": "egg tart",
  "루이보스": "rooibos tea",
  "간천엽": "beef liver and omasum",
  "디저트": "dessert",
  "백세주": "Baekseju rice wine",
  "탕평채": "mung bean jelly salad",
  "텃만꿍": "Thai shrimp cakes",
  "핫초코": "hot chocolate",
  "반미": "banh mi",
  "전병": "savory crepe",
  "주류": "alcoholic drinks",
  "짜조": "Vietnamese spring rolls",
  "참돔": "red sea bream",
  "춘권": "spring rolls",
  "플레인요거트스무디": "plain yogurt smoothie",
  "애플망고스무디": "apple mango smoothie",
  "프렌치토스트": "French toast",
  "당근케이크": "carrot cake",
  "루이보스티": "rooibos tea",
  "마르코폴로": "Marco Polo tea",
  "모닝글로리": "stir-fried morning glory",
  "뿌팟퐁커리": "Thai crab curry",
  "푸팟퐁커리": "Thai crab curry",
  "샤오롱바오": "xiaolongbao soup dumplings",
  "수수부꾸미": "pan-fried sorghum cakes",
  "가라아게": "karaage",
  "꿔보러우": "crispy sweet-and-sour pork",
  "나폴리탄": "Napolitan spaghetti",
  "미숫가루": "roasted grain drink",
  "분보싸오": "bun bo xao",
  "아란치니": "arancini",
  "카페라테": "cafe latte",
  "카프레제": "Caprese salad",
  "코울슬로": "coleslaw",
  "크루아상": "croissant",
  "티라미수": "tiramisu",
  "감바스": "gambas al ajillo",
  "감성돔": "black sea bream",
  "라즈기": "chicken in chili sauce",
  "매취순": "Maechwisun plum wine",
  "메추리": "quail",
  "소룡포": "xiaolongbao soup dumplings",
  "송화단": "century egg",
  "슈니첼": "schnitzel",
  "에비동": "shrimp tempura rice bowl",
  "유림기": "fried chicken with scallion soy sauce",
  "젤라또": "gelato",
  "참이슬": "Chamisul soju",
  "츠쿠네": "chicken meatball skewers",
  "핫도그": "hot dog",
  "껍질": "skin",
  "뷔페": "buffet",
  "비지": "ground soybean stew",
  "산적": "meat and vegetable skewers",
  "식혜": "sweet rice punch",
  "우유": "milk",
  "햇반": "instant cooked rice",
  "혀 밑": "under-tongue cut",
  "소내장탕": "beef offal soup",
  "pm5:30~9:00 주문가능시간": "orders available 5:30–9:00 pm",
  "카페 라떼": "cafe latte",
  "콩국수(여름)": "soy milk noodles (summer)",
  "손수제비": "handmade hand-torn noodle soup",
  "특설렁탕": "special ox bone soup",
  "회무침": "spicy sashimi salad",
  "회무침(대)": "spicy sashimi salad (large)",
  "회무침(중)": "spicy sashimi salad (medium)",
  "회정식": "sashimi set meal",
  "미꾸라지튀김": "fried loach",
  "계란후라이": "fried egg",
  "돈코츠라멘": "tonkotsu ramen",
  "매생이굴국밥": "seaweed and oyster soup with rice",
  "매생이굴떡국": "seaweed, oyster, and rice cake soup",
  "매생이떡국": "seaweed and rice cake soup",
  "서더리탕": "fish scraps soup",
  "아바이순대": "Abai-style Korean blood sausage",
  "아이스크림": "ice cream",
  "오렌지주스": "orange juice",
  "우거지탕": "dried cabbage soup",
  "짱뚱어탕": "mudskipper soup",
  "청경채볶음": "stir-fried bok choy",
  "한라봉차": "Hallabong citrus tea",
  "갈낙탕": "beef short rib and octopus soup",
  "고급양갈비": "premium lamb chops",
  "광동면": "Cantonese-style noodles",
  "니꾸우동": "beef udon",
  "대추차": "jujube tea",
  "대패삼겹살": "thin-sliced pork belly",
  "돌체라떼": "dolce latte",
  "마른안주": "dried bar snacks",
  "머리탕": "head-meat soup",
  "바싹불고기": "crispy grilled bulgogi",
  "사천탕수육": "Sichuan-style sweet-and-sour pork",
  "생강차": "ginger tea",
  "설농탕": "ox bone soup",
  "시골청국장": "country-style fermented soybean stew",
  "쌍화차": "ssanghwa herbal tea",
  "야끼소바": "yakisoba",
  "연어머리구이": "grilled salmon head",
  "자루소바": "zaru soba",
  "자루우동": "zaru udon",
  "전어구이": "grilled gizzard shad",
  "전어무침": "seasoned gizzard shad salad",
  "줄돔 (중)": "striped beakfish sashimi (medium)",
  "치킨난반": "chicken nanban",
  "카츠산도": "katsu sandwich",
  "코카콜라": "Coca-Cola",
  "함흥물냉면": "Hamheung-style cold noodles in broth",
  "해장라면": "hangover ramyeon",
  "허브차": "herbal tea",
  "호박죽": "pumpkin porridge",
  "가정식백반": "home-style Korean set meal",
  "꼼장어": "hagfish",
  "냉면(물,비빔)": "cold noodles (broth or spicy mixed)",
  "냉면(물/비빔)": "cold noodles (broth / spicy mixed)",
  "냉소바": "chilled soba",
  "냉칼국수": "chilled knife-cut noodles",
  "뚝불고기": "earthenware-pot bulgogi",
  "메뉴판": "menu",
  "물/비빔냉면": "cold noodles in broth / spicy mixed cold noodles",
  "물곰탕": "snailfish soup",
  "밤막걸리": "chestnut makgeolli",
  "복찜(대)": "braised pufferfish (large)",
  "생우럭매운탕": "fresh rockfish spicy stew",
  "소곱창전골": "beef small-intestine hot pot",
  "순메밀막국수": "100% buckwheat noodles",
  "스프링롤": "spring rolls",
  "양갈비살": "lamb rib meat",
  "옻오리": "lacquer-tree duck soup",
  "참소라": "whelk",
  "칼만두": "knife-cut noodles and dumplings",
  "칼만두국": "knife-cut noodle and dumpling soup",
  "한우꽃등심": "Korean beef ribeye",
  "홍차": "black tea",
  "회막국수": "buckwheat noodles with raw fish",
  "후식포함가격(커피or쥬스or아이스크림)": "price includes dessert (coffee, juice, or ice cream)",
  "바스크치즈케이크": "Basque cheesecake",
  "스팸계란후라이": "Spam and fried egg",
  "패션후르츠에이드": "passion fruit ade",
  "*맵기 1~3단계 *숯불구이": "* spice levels 1–3 * charcoal-grilled",
  "나가사키 짬뽕": "Nagasaki-style champon",
  "대게살볶음(회원가)": "stir-fried snow crab meat (member price)",
  "모든 사리 포함(공기밥 볶음밥 별도)": "all noodle add-ons included (rice and fried rice sold separately)",
  "안성(장터)국밥": "Anseong market-style soup with rice",
  "치킨카라아게": "chicken karaage",
  "페퍼로니 피자": "pepperoni pizza",
  "각재기국": "horse mackerel soup",
  "날치알주먹밥": "flying fish roe rice balls",
  "다슬기수제비": "freshwater snail hand-torn noodle soup",
  "동치미막국수": "buckwheat noodles with radish-water kimchi",
  "딸기스무디": "strawberry smoothie",
  "딸기아이스크림": "strawberry ice cream",
  "매생이굴전": "seaweed and oyster pancake",
  "반건조민어찜(중)": "braised semi-dried croaker (medium)",
  "봉골레 파스타": "clam pasta",
  "산낙지탕탕이": "chopped live octopus",
  "살코기국밥": "lean-meat soup with rice",
  "새알팥죽": "red bean porridge with rice balls",
  "새우후라이": "fried shrimp",
  "스프라이트": "Sprite",
  "얼그레이하이볼": "Earl Grey highball",
  "우거지갈비탕": "beef short rib soup with dried cabbage",
  "우육탕면": "beef noodle soup",
  "육회탕탕이": "chopped beef tartare",
  "전메뉴 포장/택배가능": "all menu items available for takeout or delivery",
  "전복팔보채(회원가)": "abalone and mixed seafood stir-fry (member price)",
  "전복해물짬뽕(회원가)": "abalone seafood noodle soup (member price)",
  "제주한라봉차": "Jeju Hallabong citrus tea",
  "주말/공휴일": "weekends / public holidays",
  "쿵파오치킨": "kung pao chicken",
  "키츠네우동": "kitsune udon",
  "팔진초면": "noodles with assorted seafood and meat",
  "팔진탕면": "assorted seafood and meat noodle soup",
  "(특)머리탕": "head-meat soup (special)",
  "(특)설농탕": "ox bone soup (special)",
  "가오리회무침": "spicy raw skate salad",
  "가자미식해": "fermented flounder",
  "게장백반": "marinated crab set meal",
  "골동면": "spicy mixed buckwheat noodles",
  "공기밥별도": "rice sold separately",
  "공기밥별도(1,000원)": "rice sold separately (₩1,000)",
  "국물떡볶이": "soupy tteokbokki",
  "굴라쉬": "goulash",
  "김치말이냉면": "cold kimchi noodles",
  "꽁치김치찌개": "saury kimchi stew",
  "녹두부침": "mung bean pancake",
  "닭개장": "spicy chicken soup",
  "더치커피": "Dutch coffee",
  "도가니(스지)탕": "ox knee cartilage and tendon soup",
  "도토리묵사발": "acorn jelly in cold broth",
  "딸기빙수": "strawberry shaved ice",
  "레몬새우": "lemon shrimp",
  "마제소바": "mazesoba",
  "매실차": "plum tea",
  "멘치카츠": "minced-meat cutlet",
  "멸치김밥": "anchovy gimbap",
  "병어구이": "grilled silver pomfret",
  "부대라면": "army-base ramyeon",
  "불낙전골": "beef bulgogi and octopus hot pot",
  "비빔모밀": "spicy mixed buckwheat noodles",
  "빠가사리매운탕(대)": "bullhead catfish spicy stew (large)",
  "빠가사리매운탕(소)": "bullhead catfish spicy stew (small)",
  "뼈다귀해장국": "pork bone hangover soup",
  "뼈없는 닭발": "boneless chicken feet",
  "사천볶음밥": "Sichuan-style fried rice",
  "사천탕수육 (대)": "Sichuan-style sweet-and-sour pork (large)",
  "사천탕수육(소)": "Sichuan-style sweet-and-sour pork (small)",
  "쇼유라멘": "shoyu ramen",
  "시락국": "dried radish greens soup",
  "쌈밥정식": "vegetable-wrap rice set meal",
  "양푼비빔밥": "large-bowl bibimbap",
  "얼음황도": "iced peaches",
  "에비텐동": "shrimp tempura rice bowl",
  "오징어다리튀김": "fried squid tentacles",
  "유자에이드": "citron ade",
  "자반구이": "grilled salted fish",
  "전기구이": "rotisserie-grilled",
  "40년 전통 \"장안동 일미간장게장\"": "40-year tradition: Jangandong Ilmi soy-marinated raw crab",
  "갈비살,육즙등심,차돌살 등등 골고루 할인된 가격으로 즐기세요.": "rib meat, juicy loin, and beef brisket assortment at a discounted price",
  "현대장칼국수 신메뉴 옹심이장칼국수 입니다.": "Hyundai Jang Kalguksu's new potato-dumpling knife-cut noodle soup",
  "치킨난방": "chicken nanban",
  "전통갈비탕": "traditional beef short rib soup",
  "줄돔 (대)": "striped beakfish sashimi (large)",
  "줄돔 (소)": "striped beakfish sashimi (small)",
  "중국냉면": "Chinese-style cold noodles",
  "중화비빔면": "Chinese-style spicy mixed noodles",
  "짬짜면": "half black bean noodles and half spicy seafood noodles",
  "참치뱃살": "tuna belly sashimi",
  "찹쌀떡": "glutinous rice cake",
  "청귤차": "green tangerine tea",
  "추어튀김": "fried loach",
  "추어튀김 (대)": "fried loach (large)",
  "콩국수 (여름메뉴)": "soy milk noodles (summer menu)",
  "탕수새우": "sweet-and-sour shrimp",
  "특양 (1인분)": "beef tripe (1 serving)",
  "필터커피": "filter coffee",
  "함흥비빔냉면": "Hamheung-style spicy mixed cold noodles",
  "활어물회": "spicy raw live-fish soup",
  "감자떡": "potato rice cake",
  "감자채전": "shredded potato pancake",
  "고사리육개장": "bracken spicy beef soup",
  "김밥(1줄)": "gimbap (1 roll)",
  "꽃등심": "ribeye",
  "내장(양)곰탕": "offal and beef tripe soup",
  "내장만": "offal only",
  "단새우": "sweet shrimp",
  "대광어회": "large olive flounder sashimi",
  "대구포": "dried cod",
  "대방어(소)": "large yellowtail (small)",
  "대방어회(소)": "large yellowtail sashimi (small)",
  "돼지생갈비(200g)": "fresh pork ribs (200g)",
  "뒷고기": "assorted pork cuts",
  "막회": "rustic sliced sashimi",
  "만두반": "half serving of dumplings",
  "면사리": "extra noodles",
  "모듬전골 (대)": "assorted hot pot (large)",
  "물,비빔냉면": "cold noodles in broth, spicy mixed cold noodles",
  "복매운탕": "spicy pufferfish stew",
  "복수육": "boiled pufferfish slices",
  "복찜(소)": "braised pufferfish (small)",
  "복찜(중)": "braised pufferfish (medium)",
  "복튀김": "fried pufferfish",
  "불짜장": "extra-spicy black bean noodles",
  "불짬뽕": "extra-spicy seafood noodle soup",
  "불짬뽕밥": "extra-spicy seafood soup with rice",
  "뿔소라": "horned turban shell",
  "새우살": "shrimp meat",
  "새우탕면": "shrimp noodle soup",
  "생아구찜 (중)": "fresh braised monkfish (medium)",
  "생연어덮밥": "fresh salmon rice bowl",
  "생우럭탕": "fresh rockfish soup",
  "소우동": "small udon",
  "손국수": "handmade noodles",
  "손두부": "handmade tofu",
  "쌈밥": "rice with vegetable wraps",
  "양밥": "beef tripe rice",
  "어죽": "fish porridge",
  "오징어통찜": "whole steamed squid",
  "왕새우구이": "grilled jumbo shrimp",
  "전복장 정식": "soy-marinated abalone set meal",
  "족탕": "pig's trotter soup",
  "찹쌀탕수육": "glutinous-rice-battered sweet-and-sour pork",
  "촌두부": "country-style tofu",
  "콘치즈": "corn cheese",
  "콩물": "soy milk",
  "통갈치구이(대)": "whole grilled hairtail (large)",
  "특복국": "special pufferfish soup",
  "팥죽": "red bean porridge",
  "햄사리": "extra ham",
  "홍어애탕": "fermented skate liver soup",
  "산미가 강하지도, 너무 다크하지 않으며 밸런스가 좋은 커피입니다": "well-balanced coffee with moderate acidity and roast",
  "전복,소고기,낙지를 드시기 편하게 잘게 썰어 비법양념을 더해 감칠맛나는 낙지요리": "finely chopped abalone, beef, and octopus with house seasoning",
  "고궁의 전통 메뉴를 세트로 드실 있는 세트메뉴 (2인기준) 비빔밥 변경 가능(추가금 있음)": "traditional Gogung set for two; bibimbap substitutions may cost extra",
  "순살치킨이랑 달라요 중심뼈는 있어요": "contains the center bone; different from boneless chicken",
  "예약필요없이.주문후10분즘이면 나와요": "no reservation needed; served about 10 minutes after ordering",
  "매운맛,보통맛(신라면기준),순한맛(고추X)": "spicy, regular (Shin Ramyeon level), or mild (no chili)",
  "소프트쉘크랩커리": "soft-shell crab curry",
  "갈릭 페퍼 슈림프": "garlic pepper shrimp",
  "마구로 타르타르": "tuna tartare",
  "서리태콩국수(여름한정)": "black soybean noodles (summer only)",
  "소고기 양상추 쌈(회원가)": "beef lettuce wraps (member price)",
  "스타터(관자,참외)": "starter (scallop and Korean melon)",
  "스타터(채소,참꺠)": "starter (vegetables and sesame)",
  "아마트리치아나 스파게티": "spaghetti all'amatriciana",
  "이베리코프레사": "Iberico presa",
  "카라멜마끼아또": "caramel macchiato",
  "태국대표 치킨커리라이스": "Thai chicken curry rice",
  "태국식 소고기 아롱사태쌀국수": "Thai beef shank rice noodle soup",
  "- 순한맛 / 중간맛 / 매운맛 선택 가능 - 곱배기 추가 시 3,000원": "choose mild / medium / spicy; large portion +₩3,000",
  "매쉬포테이토": "mashed potatoes",
  "먹물 카펠리니": "squid ink capellini",
  "봉골레 링귀니": "clam linguine",
  "비프 타르타르": "beef tartare",
  "뿌님팟퐁커리": "Thai soft-shell crab curry",
  "상하이롤 플래터": "Shanghai roll platter",
  "애플시나몬티": "apple cinnamon tea",
  "요거트스무디": "yogurt smoothie",
  "카이란 소고기 볶음(회원가)": "stir-fried gai lan and beef (member price)",
  "카이란 전복(회원가)": "gai lan and abalone (member price)",
  "커리부어스트": "currywurst",
  "태국식 공심채볶음": "Thai stir-fried morning glory",
  "태국식 파파야샐러드": "Thai papaya salad",
  "프렌치프라이": "french fries",
  "플레인요거트": "plain yogurt",
  "한일관 신선로": "Hanilgwan royal hot pot",
  "핫/아이스 초코": "hot / iced chocolate",
  "광어 카르파치오": "olive flounder carpaccio",
  "깐쇼대하(회원가)": "sweet and spicy jumbo shrimp (member price)",
  "깐풍대하(회원가)": "spicy garlic jumbo shrimp (member price)",
  "꼬르동브루": "cordon bleu",
  "꿍팟퐁커리": "Thai shrimp curry",
  "도리뱅뱅이": "crispy freshwater fish with spicy sauce",
  "마르게리따피자": "Margherita pizza",
  "밀푀유나베": "mille-feuille hot pot",
  "삶은돼지고기&어리굴젓": "boiled pork and salted oysters",
  "아쿠아파짜": "acqua pazza",
  "오이탕탕이": "smashed cucumber salad",
  "완도 전복 리조또": "Wando abalone risotto",
  "이소베마끼": "isobe maki",
  "전복 율무 리조또,샐러드": "abalone and Job's tears risotto, salad",
  "참옥돔(메인)": "tilefish (main)",
  "초코바게트": "chocolate baguette",
  "전복 리조또": "abalone risotto",
  "후토마키(반줄)": "futomaki (half roll)",
  "후토마끼(반줄)": "futomaki (half roll)",
  "안거미": "angeomi beef cut",
  "짝갈비살": "paired rib meat",
  "巨大 양념갈비": "Geodae marinated short ribs",
};

/**
 * Culinary building blocks used for unseen compounds. Entries deliberately
 * avoid uncertain species: ambiguous house words remain romanized.
 */
export const MENU_LEXICON: Readonly<Record<string, string>> = {
  // Multi-word culinary forms (longest match wins).
  "숯불구이": "charcoal-grilled", "소금구이": "salt-grilled", "양념구이": "seasoned grilled",
  "간장구이": "soy-glazed grilled", "직화구이": "flame-grilled", "화로구이": "brazier-grilled",
  "모둠구이": "assorted grilled", "모듬구이": "assorted grilled", "생선구이": "grilled fish",
  "간장양념": "soy seasoning", "매운양념": "spicy seasoning", "특제소스": "house sauce",
  "매콤달콤": "sweet and spicy", "새콤달콤": "sweet and tangy", "얼큰해물": "spicy seafood",
  "해물누룽지탕": "crispy rice seafood soup", "누룽지탕": "crispy rice soup",
  "소고기국밥": "beef soup with rice", "소머리국밥": "ox head soup with rice",
  "내장국밥": "offal soup with rice", "순대국밥": "blood sausage soup with rice",
  "돼지국밥": "pork soup with rice", "굴국밥": "oyster soup with rice",
  "김치찌개": "kimchi stew", "된장찌개": "soybean paste stew", "순두부찌개": "soft tofu stew",
  "동태찌개": "pollock stew", "부대찌개": "army-base stew", "청국장찌개": "fermented soybean stew",
  "고추장찌개": "chili paste stew", "참치찌개": "tuna stew", "해물찌개": "seafood stew",
  "비빔냉면": "spicy mixed cold noodles", "물냉면": "cold noodles in broth", "회냉면": "cold noodles with raw fish",
  "비빔막국수": "spicy mixed buckwheat noodles", "물막국수": "buckwheat noodles in cold broth",
  "바지락칼국수": "clam knife-cut noodle soup", "들깨칼국수": "perilla seed knife-cut noodle soup",
  "해물칼국수": "seafood knife-cut noodle soup", "닭칼국수": "chicken knife-cut noodle soup",
  "멸치국수": "anchovy noodle soup", "비빔국수": "spicy mixed noodles", "잔치국수": "banquet noodle soup",
  "콩국수": "noodles in cold soy milk", "쌀국수": "rice noodle soup", "고기국수": "meat noodle soup",
  "제육볶음": "spicy stir-fried pork", "낙지볶음": "spicy stir-fried octopus",
  "오징어볶음": "spicy stir-fried squid", "주꾸미볶음": "spicy stir-fried webfoot octopus",
  "쭈꾸미볶음": "spicy stir-fried webfoot octopus", "닭볶음탕": "spicy braised chicken",
  "닭도리탕": "spicy braised chicken", "새우볶음밥": "shrimp fried rice",
  "김치볶음밥": "kimchi fried rice", "게살볶음밥": "crab fried rice", "계란볶음밥": "egg fried rice",
  "육회비빔밥": "beef tartare bibimbap", "돌솥비빔밥": "hot stone pot bibimbap",
  "전주비빔밥": "Jeonju-style bibimbap", "산채비빔밥": "wild greens bibimbap",
  "회덮밥": "sashimi rice bowl", "장어덮밥": "grilled eel rice bowl", "제육덮밥": "spicy pork rice bowl",
  "오징어덮밥": "spicy squid rice bowl", "낙지덮밥": "spicy octopus rice bowl",
  "소불고기": "beef bulgogi", "돼지불고기": "pork bulgogi", "뚝배기불고기": "earthenware-pot bulgogi",
  "돼지갈비": "pork ribs", "소갈비": "beef short ribs", "양념갈비": "marinated short ribs",
  "갈비찜": "braised short ribs", "갈비탕": "beef short rib soup", "떡갈비": "grilled short-rib patties",
  "고등어구이": "grilled mackerel", "갈치구이": "grilled hairtail", "조기구이": "grilled yellow croaker",
  "황태구이": "grilled dried pollock", "더덕구이": "grilled deodeok root", "장어구이": "grilled eel",
  "고등어조림": "braised mackerel", "갈치조림": "braised hairtail", "두부조림": "braised tofu",
  "연어회": "salmon sashimi", "광어회": "olive flounder sashimi", "우럭회": "rockfish sashimi",
  "도미회": "sea bream sashimi", "참치회": "tuna sashimi", "전복회": "raw abalone",
  "모둠회": "assorted sashimi", "모듬회": "assorted sashimi", "활어회": "live-fish sashimi",
  "해물파전": "seafood and green onion pancake", "김치전": "kimchi pancake", "감자전": "potato pancake",
  "부추전": "chive pancake", "굴전": "oyster pancake", "육전": "pan-fried battered beef slices",
  "녹두전": "mung bean pancake", "모둠전": "assorted savory pancakes", "모듬전": "assorted savory pancakes",
  "새우튀김": "shrimp tempura", "오징어튀김": "fried squid", "고구마튀김": "sweet potato tempura",
  "야채튀김": "vegetable tempura", "감자튀김": "french fries", "모둠튀김": "assorted fried items",
  "모듬튀김": "assorted fried items", "닭강정": "sweet crispy chicken",
  "후라이드치킨": "fried chicken", "프라이드치킨": "fried chicken", "양념치킨": "seasoned fried chicken",
  "간장치킨": "soy-glazed chicken", "반반치킨": "half-and-half chicken",
  "고기만두": "meat dumplings", "김치만두": "kimchi dumplings", "새우만두": "shrimp dumplings",
  "군만두": "fried dumplings", "찐만두": "steamed dumplings", "물만두": "boiled dumplings",
  "왕만두": "large dumplings", "만두국": "dumpling soup", "만둣국": "dumpling soup",
  "떡만두국": "rice cake and dumpling soup", "떡만둣국": "rice cake and dumpling soup",
  "계란말이": "rolled omelet", "계란찜": "steamed eggs", "계란탕": "egg soup",
  "두부김치": "tofu with stir-fried kimchi", "골뱅이무침": "spicy sea-snail salad",
  "도토리묵": "acorn jelly", "메밀전병": "buckwheat rolls", "문어숙회": "blanched octopus",
  "꼬리곰탕": "oxtail soup", "도가니탕": "ox knee cartilage soup", "설렁탕": "ox bone soup",
  "삼계탕": "ginseng chicken soup", "감자탕": "pork back-bone stew", "추어탕": "loach soup",
  "매운탕": "spicy fish stew", "꽃게탕": "blue crab stew", "대구탕": "cod soup",
  "장어탕": "eel soup", "알탕": "fish roe stew", "내장탕": "offal soup", "해장국": "hangover soup",
  "육개장": "spicy beef soup", "미역국": "seaweed soup", "황태국": "dried pollock soup",
  "북엇국": "dried pollock soup", "콩나물국": "soybean sprout soup",
  "아구찜": "spicy braised monkfish", "아귀찜": "spicy braised monkfish", "해물찜": "spicy braised seafood",
  "꽃게찜": "steamed blue crab", "김치찜": "braised kimchi", "닭백숙": "whole chicken soup",
  "간장게장": "soy-marinated raw crab", "양념게장": "spicy marinated raw crab",
  "홍어삼합": "fermented skate with pork and kimchi", "오징어순대": "stuffed squid",
  "산낙지": "live octopus", "물회": "spicy raw seafood soup", "전복죽": "abalone porridge",
  "짜장면": "black bean noodles", "자장면": "black bean noodles", "간짜장": "dry-style black bean noodles",
  "유니짜장": "minced-meat black bean noodles", "삼선짜장": "premium seafood black bean noodles",
  "삼선짬뽕": "premium seafood noodle soup", "고추짬뽕": "spicy chili seafood noodle soup",
  "짬뽕밥": "spicy seafood soup with rice", "짜장밥": "black bean sauce with rice",
  "잡채밥": "stir-fried glass noodles with rice", "마파두부밥": "mapo tofu with rice",
  "유산슬밥": "shredded seafood and meat stir-fry with rice", "잡탕밥": "rice with assorted seafood and vegetables",
  "탕수육": "sweet-and-sour pork", "깐풍기": "spicy garlic fried chicken", "깐풍육": "spicy garlic pork",
  "깐풍새우": "spicy garlic shrimp", "깐쇼새우": "sweet and spicy crispy shrimp",
  "마파두부": "mapo tofu", "고추잡채": "stir-fried peppers and meat", "유산슬": "shredded seafood and meat stir-fry",
  "팔보채": "stir-fried mixed seafood and vegetables", "난자완스": "braised meatballs", "동파육": "Dongpo-style braised pork belly",
  "라조기": "chicken in chili sauce", "양장피": "seafood and vegetables with mustard sauce",
  "기스면": "shredded chicken noodle soup", "울면": "thick seafood noodle soup",
  "등심돈까스": "pork loin cutlet", "안심돈까스": "pork tenderloin cutlet", "치즈돈까스": "cheese pork cutlet",
  "생선까스": "fish cutlet", "치킨까스": "chicken cutlet", "함박스테이크": "hamburger steak",
  "토마토파스타": "tomato pasta", "크림파스타": "cream pasta", "봉골레파스타": "clam pasta",
  "고르곤졸라": "Gorgonzola", "마르게리타": "Margherita", "알리오올리오": "aglio e olio",
  "아이스아메리카노": "iced Americano", "바닐라라떼": "vanilla latte", "카페라떼": "cafe latte",
  "카페모카": "cafe mocha", "초코라떼": "chocolate latte", "녹차라떼": "green tea latte",
  "말차라떼": "matcha latte", "고구마라떼": "sweet potato latte", "딸기라떼": "strawberry latte",
  "레몬에이드": "lemonade", "자몽에이드": "grapefruit ade", "청포도에이드": "green grape ade",

  // Ingredients, cuts, preparations, and dish forms for novel compounds.
  "국내산": "domestic", "제주산": "Jeju", "자연산": "wild-caught", "한우": "Korean beef",
  "흑돼지": "black pork", "돼지고기": "pork", "소고기": "beef", "닭고기": "chicken",
  "돼지": "pork", "소고": "beef", "고기": "meat", "생고기": "fresh meat",
  "삼겹살": "pork belly", "오겹살": "five-layer pork belly", "목살": "pork neck", "항정살": "pork jowl",
  "가브리살": "pork cheek", "갈매기살": "pork skirt meat", "등심": "loin", "안심": "tenderloin",
  "갈비살": "rib meat", "차돌박이": "beef brisket", "우삼겹": "beef short plate",
  "곱창": "small intestines", "대창": "large intestines", "막창": "intestines", "양곱창": "tripe and intestines",
  "내장": "offal", "도가니": "ox knee cartilage", "꼬리": "oxtail", "소머리": "ox head",
  "머리고기": "head-meat slices", "편육": "sliced pressed meat", "수육": "boiled meat slices",
  "족발": "braised pork trotters", "보쌈": "boiled pork wraps", "육회": "beef tartare", "불고기": "bulgogi",
  "닭발": "chicken feet", "닭똥집": "chicken gizzards", "닭한마리": "whole chicken hot pot",
  "오리": "duck", "훈제오리": "smoked duck", "백숙": "whole poultry soup",
  "고등어": "mackerel", "갈치": "hairtail", "조기": "yellow croaker", "굴비": "dried yellow croaker",
  "대구": "cod", "동태": "pollock", "명태": "pollock", "황태": "dried pollock", "북어": "dried pollock",
  "광어": "olive flounder", "우럭": "rockfish", "도미": "sea bream", "연어": "salmon", "참치": "tuna",
  "방어": "yellowtail", "민어": "croaker", "도다리": "flounder", "농어": "sea bass", "장어": "eel",
  "아구": "monkfish", "아귀": "monkfish", "홍어": "fermented skate", "생선": "fish",
  "해산물": "seafood", "해물": "seafood", "전복": "abalone", "소라": "whelk", "골뱅이": "sea snail",
  "미더덕": "sea pineapple", "조개": "shellfish", "바지락": "clam", "가리비": "scallop", "홍합": "mussel",
  "꽃게": "blue crab", "게살": "crab meat", "대게": "snow crab", "킹크랩": "king crab",
  "새우": "shrimp", "대하": "large shrimp", "오징어": "squid", "한치": "spear squid",
  "낙지": "octopus", "주꾸미": "webfoot octopus", "쭈꾸미": "webfoot octopus", "문어": "octopus",
  "멍게": "sea squirt", "해삼": "sea cucumber", "성게": "sea urchin", "생선알": "fish roe",
  "김치": "kimchi", "묵은지": "aged kimchi", "깍두기": "radish kimchi", "열무": "young-radish kimchi",
  "배추": "napa cabbage", "무생채": "seasoned radish", "무뼈": "boneless", "감자": "potato", "고구마": "sweet potato", "옥수수": "corn",
  "버섯": "mushroom", "표고": "shiitake", "송이": "pine mushroom", "능이": "black tiger paw mushroom",
  "더덕": "deodeok root", "도라지": "bellflower root", "우엉": "burdock root", "연근": "lotus root",
  "부추": "chive", "파채": "seasoned scallions", "파김치": "green onion kimchi", "마늘": "garlic", "고추": "chili", "청양고추": "Cheongyang chili",
  "콩나물": "soybean sprouts", "숙주": "mung bean sprouts", "나물": "seasoned greens", "산채": "wild greens",
  "두부": "tofu", "순두부": "soft tofu", "유부": "fried tofu", "들깨": "perilla seed",
  "메밀": "buckwheat", "보리": "barley", "현미": "brown rice", "흑미": "black rice",
  "솥밥": "pot rice", "돌솥": "hot stone pot", "뚝배기": "earthenware pot", "누룽지": "scorched rice",
  "계란": "egg", "달걀": "egg", "치즈": "cheese", "크림": "cream", "버터": "butter",
  "떡볶이": "tteokbokki", "어묵": "fish cake", "오뎅": "fish cake", "순대": "Korean blood sausage",
  "만두": "dumplings", "국수": "noodles", "칼국수": "knife-cut noodle soup", "막국수": "buckwheat noodles",
  "냉면": "cold noodles", "라면": "ramyeon", "라멘": "ramen", "우동": "udon", "소바": "soba",
  "쫄면": "spicy chewy noodles", "파스타": "pasta", "스파게티": "spaghetti", "잡채": "stir-fried glass noodles",
  "짜장": "black bean sauce", "짬뽕": "spicy seafood noodle soup", "카레": "curry",
  "초밥": "sushi", "스시": "sushi", "사시미": "sashimi", "김밥": "gimbap",
  "돈가스": "pork cutlet", "돈까스": "pork cutlet", "카츠": "cutlet", "스테이크": "steak",
  "피자": "pizza", "햄버거": "hamburger", "버거": "burger", "샌드위치": "sandwich", "샐러드": "salad",
  "스프": "soup", "수프": "soup", "국밥": "soup with rice", "곰탕": "beef bone soup",
  "찌개": "stew", "전골": "hot pot",
  "덮밥": "rice bowl", "비빔밥": "bibimbap", "볶음밥": "fried rice", "백반": "Korean set meal",
  "한정식": "Korean set menu", "정식": "set meal", "도시락": "lunch box", "코스": "course",
  "세트메뉴": "set menu", "세트": "set", "단품": "a la carte", "사이드": "side",
  "구이": "grilled", "볶음": "stir-fried", "조림": "braised",
  "튀김": "fried", "부침": "pan-fried", "무침": "seasoned salad",
  "숙회": "blanched", "샤브샤브": "shabu-shabu", "샤브": "shabu-shabu", "철판": "griddle",
  "숯불": "charcoal-grilled", "직화": "flame-grilled", "훈제": "smoked", "숙성": "aged",
  "생맥주": "draft beer", "생과일": "fresh fruit", "양념": "seasoned", "간장": "soy sauce", "소금": "salt", "고추장": "chili paste",
  "된장": "soybean paste", "마라": "mala", "매운": "spicy", "매콤": "spicy", "얼큰": "spicy",
  "담백": "mild", "순한": "mild", "달콤": "sweet", "새콤": "tangy", "바삭": "crispy",
  "왕갈비": "large ribs", "특대": "extra large", "곱빼기": "large portion", "곱배기": "large portion",
  "모둠": "assorted", "모듬": "assorted", "스페셜": "special", "특선": "special", "추천": "recommended",
  "대표": "signature", "시그니처": "signature", "기본": "regular", "반반": "half-and-half", "추가": "extra",
  "점심특선": "lunch special", "점심": "lunch", "런치": "lunch", "저녁": "dinner", "디너": "dinner",
  "계절메뉴": "seasonal menu", "계절": "seasonal", "오늘": "today's", "주말": "weekend", "평일": "weekday",
  "포장": "takeout", "메뉴": "menu", "선택": "choice", "리필": "refill", "무료": "free",
  "주문": "order", "가능": "available", "불가": "unavailable", "예약필수": "reservation required",
  "예약": "reservation", "필수": "required", "이상": "or more", "이탈리안": "Italian",
  "카페": "cafe", "아이스크림": "ice cream", "오렌지": "orange", "생강": "ginger",
  "돈코츠": "tonkotsu", "계란후라이": "fried egg", "청경채": "bok choy", "대패": "thin-sliced",
  "매생이": "seaweed", "우거지": "dried cabbage", "여름": "summer", "한라봉": "Hallabong citrus",
  "갈비": "ribs", "차돌": "beef brisket", "삼겹": "pork belly", "닭": "chicken",
  "수제": "handmade", "사리": "extra noodles", "비빔": "spicy mixed", "야채": "vegetables",
  "치킨": "chicken", "토마토": "tomato", "두루치기": "spicy stir-fried meat", "뼈": "bone",
  "접시": "platter", "제주": "Jeju", "메기": "catfish", "요리": "dish", "주물럭": "marinated stir-fry",
  "빵": "bread", "미니": "mini", "오마카세": "chef's tasting menu", "쟁반": "platter",
  "한마리": "whole", "한접시": "one platter", "반마리": "half", "반접시": "half platter",
  "꼬치": "skewers", "가자미": "flounder", "사골": "beef bone broth", "통닭": "whole fried chicken",
  "양지": "brisket", "한돈": "Korean pork", "소스": "sauce", "순살": "boneless",
  "어린이": "children's", "세꼬시": "bone-in sashimi", "지리": "clear fish soup", "껍데기": "pork skin",
  "명란": "pollock roe", "옛날": "old-fashioned", "주먹밥": "rice balls", "트러플": "truffle",
  "보통": "regular", "살치살": "chuck flap tail", "삼치": "Spanish mackerel", "온": "warm",
  "아나고": "conger eel", "민물": "freshwater", "간재미": "skate", "베이컨": "bacon",
  "안창살": "beef outside skirt", "선지": "ox blood", "프리미엄": "premium", "들기름": "perilla oil",
  "맛보기": "tasting portion", "삼합": "three-item platter", "식사": "meal", "포함": "included",
  "고로케": "croquette", "서대": "tongue sole", "시래기": "dried radish greens", "소면": "thin wheat noodles",
  "딸기": "strawberry", "후라이드": "fried chicken", "안주": "bar food", "특수부위": "special cuts",
  "곤드레": "seasoned thistle greens", "토종": "native-breed", "한방": "medicinal-herb",
  "아메리카노": "Americano", "에스프레소": "espresso", "카푸치노": "cappuccino", "라떼": "latte",
  "모카": "mocha", "커피": "coffee", "밀크티": "milk tea", "아이스티": "iced tea",
  "에이드": "ade", "주스": "juice", "쥬스": "juice", "콜라": "cola", "사이다": "lemon-lime soda",
  "음료수": "soft drink", "음료": "drink", "맥주": "beer", "소주": "soju",
  "막걸리": "makgeolli rice wine", "동동주": "dongdongju rice wine", "청하": "Cheongha rice wine", "와인": "wine",
};

const LEXICON_ENTRIES = Array.from(new Map([
  ...Object.entries(MENU_LEXICON),
  ...Object.entries(EXACT_MENU_TRANSLATIONS),
]).entries()).sort(
  ([left], [right]) => right.length - left.length || left.localeCompare(right, "ko")
);
const LEXICON_BY_INITIAL = new Map<string, Array<[string, string]>>();
for (const entry of LEXICON_ENTRIES) {
  const bucket = LEXICON_BY_INITIAL.get(entry[0][0]) ?? [];
  bucket.push(entry);
  LEXICON_BY_INITIAL.set(entry[0][0], bucket);
}

const MENU_SUFFIXES: Readonly<Record<string, string>> = {
  "밥": "rice",
  "면": "noodles",
  "죽": "porridge",
  "탕": "soup",
  "국": "soup",
  "찜": "steamed or braised",
  "전": "savory pancake",
  "회": "sashimi",
  "롤": "roll",
};

function findLexiconEntry(value: string, cursor: number): readonly [string, string] | undefined {
  const regular = LEXICON_BY_INITIAL.get(value[cursor])?.find(([korean]) => value.startsWith(korean, cursor));
  if (regular) return regular;
  const suffixCharacter = value[cursor];
  const suffix = MENU_SUFFIXES[suffixCharacter];
  if (suffix && !/[가-힣]/.test(value[cursor + 1] ?? "")) return [suffixCharacter, suffix];
  return undefined;
}

function romanizeHangul(value: string) {
  return value.replace(/[가-힣]+/g, word => {
    const converted = Array.from(word, syllable => {
      const code = syllable.charCodeAt(0) - 0xac00;
      return `${INITIAL[Math.floor(code / 588)]}${VOWEL[Math.floor((code % 588) / 28)]}${FINAL[code % 28]}`;
    }).join("");
    return converted.charAt(0).toUpperCase() + converted.slice(1);
  });
}

function normalizeSource(value: string) {
  return value
    .normalize("NFC")
    .replace(/[（]/g, "(")
    .replace(/[）]/g, ")")
    .replace(/[／]/g, "/")
    .replace(/[～〜]/g, "~")
    .replace(/\s+/g, " ")
    .trim();
}

function translateMetadata(value: string) {
  return value
    .replace(/([\d,]+)\s*(?:원)?\s*~\s*([\d,]+)\s*원/g, "₩$1–₩$2")
    .replace(/([\d,]+)\s*원/g, "₩$1")
    .replace(/(\d+)\s*인\s*이상/g, "for $1+ people")
    .replace(/(\d+)\s*인분/g, (_, count: string) => `${count} ${count === "1" ? "serving" : "servings"}`)
    .replace(/(\d+)\s*인(?=세트|정식|코스)/g, "for $1 ")
    .replace(/(\d+)\s*인(?![가-힣])/g, (_, count: string) => `for ${count} ${count === "1" ? "person" : "people"}`)
    .replace(/(\d+)\s*개(?![가-힣])/g, "$1 pieces")
    .replace(/(\d+)\s*마리(?![가-힣])/g, "$1 whole")
    .replace(/(\d+)\s*잔(?![가-힣])/g, "$1 glasses")
    .replace(/(\d+)\s*병(?![가-힣])/g, "$1 bottles")
    .replace(/(\d+)\s*조각(?![가-힣])/g, "$1 pieces")
    .replace(/\(\s*대\s*\)/g, "(large)")
    .replace(/\(\s*중\s*\)/g, "(medium)")
    .replace(/\(\s*소\s*\)/g, "(small)")
    .replace(/\(\s*특\s*\)/g, "(special)")
    .replace(/\(\s*보통\s*\)/g, "(regular)")
    .replace(/(^|[\s/·,+()-])대(?=$|[\s/·,+()-])/g, "$1large")
    .replace(/(^|[\s/·,+()-])중(?=$|[\s/·,+()-])/g, "$1medium")
    .replace(/(^|[\s/·,+()-])소(?=$|[\s/·,+()-])/g, "$1small")
    .replace(/가격\s*변동|변동가/g, "price varies")
    .replace(/시가/g, "market price");
}

function cleanEnglish(value: string) {
  return value
    .replace(/\s+/g, " ")
    .replace(/\s+([,.)])/g, "$1")
    .replace(/([(])\s+/g, "$1")
    .replace(/\s*([/·;])\s*/g, " $1 ")
    .replace(/\s*–\s*/g, "–")
    .trim();
}

export interface MenuTranslationDetails {
  english: string;
  exact: boolean;
  totalHangulCharacters: number;
  translatedHangulCharacters: number;
  unknownSegments: string[];
}

/** Translate while exposing enough detail for the deterministic coverage audit. */
export function translateMenuNameDetailed(value: string): MenuTranslationDetails {
  const source = normalizeSource(String(value ?? ""));
  const totalHangulCharacters = (source.match(/[가-힣]/g) ?? []).length;
  if (!source) {
    return { english: "", exact: false, totalHangulCharacters: 0, translatedHangulCharacters: 0, unknownSegments: [] };
  }

  const exactTranslation = EXACT_MENU_TRANSLATIONS[source];
  if (exactTranslation) {
    return {
      english: exactTranslation,
      exact: true,
      totalHangulCharacters,
      translatedHangulCharacters: totalHangulCharacters,
      unknownSegments: [],
    };
  }

  const prepared = translateMetadata(source);
  const output: string[] = [];
  const unknownSegments: string[] = [];
  let translatedHangulCharacters = totalHangulCharacters - (prepared.match(/[가-힣]/g) ?? []).length;
  let cursor = 0;

  while (cursor < prepared.length) {
    const character = prepared[cursor];
    if (!/[가-힣]/.test(character)) {
      output.push(character);
      cursor += 1;
      continue;
    }

    const matched = findLexiconEntry(prepared, cursor);
    if (matched) {
      output.push(` ${matched[1]} `);
      translatedHangulCharacters += matched[0].length;
      cursor += matched[0].length;
      continue;
    }

    let end = cursor + 1;
    while (end < prepared.length && /[가-힣]/.test(prepared[end])) {
      const hasKnownTerm = Boolean(findLexiconEntry(prepared, end));
      if (hasKnownTerm) break;
      end += 1;
    }
    const unknown = prepared.slice(cursor, end);
    unknownSegments.push(unknown);
    output.push(` ${romanizeHangul(unknown)} `);
    cursor = end;
  }

  return {
    english: cleanEnglish(output.join("")),
    exact: false,
    totalHangulCharacters,
    translatedHangulCharacters: Math.min(totalHangulCharacters, translatedHangulCharacters),
    unknownSegments,
  };
}

export function getEnglishMenuName(value: string) {
  return translateMenuNameDetailed(value).english;
}

